
FIND_PATH(OPENSSL_INCLUDE_DIR openssl/ssl.h )

FIND_LIBRARY(OPENSSL_LIB1 NAMES ssl ssleay32 ssleay32MD )
FIND_LIBRARY(OPENSSL_LIB2 NAMES crypto )

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OPENSSL DEFAULT_MSG OPENSSL_LIB1 OPENSSL_LIB2 OPENSSL_INCLUDE_DIR)

IF (OPENSSL_FOUND)
  SET(OPENSSL_LIBRARIES ${OPENSSL_LIB1} ${OPENSSL_LIB2}  )
  SET(OPENSSL_INCLUDE_DIRS ${OPENSSL_INCLUDE_DIR})
ELSE(OPENSSL_FOUND)
  SET(OPENSSL_LIBRARIES)
  SET(OPENSSL_INCLUDE_DIRS)
ENDIF(OPENSSL_FOUND)

